version: "3.5"
services:
  yugabytedb:
    container_name: temporal-yugabytedb
    image: yugabytedb/yugabyte
    command: yugabyted start --background=false --tserver_flags=ysql_colocate_database_by_default=true,yb_enable_read_committed_isolation=true,enable_deadlock_detection=true,enable_wait_queues=true,ysql_pg_conf_csv={yb_bnl_batch_size=1024,yb_enable_optimizer_statistics=on,yb_enable_base_scans_cost_model=on}
    networks:
      - temporal-network
    ports:
      - 5433:5433
      - 15433:15433
    volumes:
      - /root/var
  temporal:
    container_name: temporal
    depends_on:
      - yugabytedb
    environment:
      - DB=postgresql
      - DB_PORT=5433
      - POSTGRES_USER=yugabyte
      - POSTGRES_PWD=yugabyte
      - POSTGRES_SEEDS=yugabytedb
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - temporal-network
    ports:
      - 7233:7233
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    labels:
      kompose.volume.type: configMap
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_VERSION}
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - temporal-network
    ports:
      - 8080:8080
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
